version: v2.0.1-{branch}-{build}

environment:
  NSIS_ROOT: C:\Program Files (x86)\NSIS
  matrix:
  - QTDIR: C:\Qt\5.5\msvc2013_64
    CMAKE_GENERATOR: Visual Studio 12 Win64
  - QTDIR: C:\Qt\5.5\msvc2013
    CMAKE_GENERATOR: Visual Studio 12

install:
    - choco install nsis -pre
    - set PATH=%PATH%;%QTDIR%/bin;%NSIS_ROOT%
    - git clone https://github.com/neurosuite/libneurosuite.git
    - cd libneurosuite
    - cmake -G "%CMAKE_GENERATOR%" .
    - cmake --build . --target INSTALL
    - cd ..
    - git clone https://github.com/neurosuite/libcbsdk.git
    - cd libcbsdk
    - cmake -G "%CMAKE_GENERATOR%" .
    - cmake --build . --target INSTALL
    - cd ..

build_script:
    - mkdir build
    - cd build
    - cmake -D WITH_CEREBUS=ON -G "%CMAKE_GENERATOR%" ..
    - cmake --build . --target PACKAGE

test: off

artifacts:
  - path: build\neuroscope-*.exe
    name: NSIS Installer

deploy:
  - provider: GitHub
    auth_token:
      secure: L3YxjzNdS3PGjngFslfEMtvuWDL5Jf5ZmMGvt2mjT8xGN9f2U/k2SvQyZo78CB9F
    on:
      appveyor_repo_tag: true
