version: v2.1.0-{branch}-{build}

environment:
  NSIS_ROOT: C:\Program Files (x86)\NSIS
  CMAKE_TOOLKIT: v120_xp
  matrix:
  - QTDIR: C:\Qt\5.5\msvc2013_64
    CMAKE_GENERATOR: Visual Studio 12 Win64
  - QTDIR: C:\Qt\5.5\msvc2013
    CMAKE_GENERATOR: Visual Studio 12

install:
    - choco install nsis -pre
    - set PATH=%PATH%;%QTDIR%/bin;%NSIS_ROOT%
    - git clone https://github.com/neurosuite/libneurosuite.git
    - cd libneurosuite
    - cmake -G "%CMAKE_GENERATOR%" -T "%CMAKE_TOOLKIT%" .
    - cmake --build . --target INSTALL --config Release
    - cd ..
    - git clone https://github.com/neurosuite/libcbsdk.git
    - cd libcbsdk
    - cmake -G "%CMAKE_GENERATOR%" -T "%CMAKE_TOOLKIT%" .
    - cmake --build . --target INSTALL --config Release
    - cd ..

build_script:
    - mkdir build
    - cd build
    - cmake -D WITH_CEREBUS=ON -G "%CMAKE_GENERATOR%" -T "%CMAKE_TOOLKIT%" ..
    - cmake --build . --target PACKAGE --config Release

test: off

artifacts:
  - path: build\neuroscope-*.exe
    name: NSIS Installer

deploy:
  - provider: GitHub
    auth_token:
      secure: NIUGf3T938Kltzo+d2hsS82EoMjJ+12kv42KU02/XG4m4GF5WxkLGuedXuFV7yQx
    on:
      appveyor_repo_tag: true
