language: cpp

sudo: true
dist: trusty

matrix:
  include:
  - os: linux
    env: QT_VERSION=qt4
    compiler: clang
    addons:
      apt:
        packages:
          - libqt4-dev
  - os: linux
    env: QT_VERSION=qt4
    compiler: gcc
    addons:
      apt:
        packages:
          - libqt4-dev
  - os: linux
    env: QT_VERSION=qt5 TRAVIS_DEPLOY=y
    compiler: clang
    addons:
      apt:
        packages:
          - qtbase5-dev
  - os: linux
    env: QT_VERSION=qt5
    compiler: gcc
    addons:
      apt:
        packages:
          - qtbase5-dev
  - os: osx
    env: QT_VERSION=qt5 TRAVIS_DEPLOY=y
    compiler: clang

install: source .travis/install.sh

script: ./.travis/script.sh

deploy:
  provider: releases
  api_key:
    secure: LdMU6bfPozM1sD+k/GVcTbmh+tlDuLzyQKbS38+3KOYhoVFVlOA2d1vymDI8BmQ66xSYa6yGBZ3Zu3MbV+aiukSNMp+QnS4q0mySxq7iUNdhEAI9a9GcljYvxo/Oj3BeJpksX6JgIhZK06wnafb1E6jdh6i1d+DldMK36PjMeVg=
  skip_cleanup: true
  file_glob: true
  file:
    - build/neuroscope*.deb
    - build/neuroscope*.dmg
  on:
    tags: true
    condition: "$TRAVIS_DEPLOY = y"
