language: cpp

sudo: true
dist: trusty

matrix:
  include:
  - os: linux
    env: QT_VERSION=qt4
    compiler: clang
    addons:
      apt:
        packages:
          - libqt4-dev
  - os: linux
    env: QT_VERSION=qt4
    compiler: gcc
    addons:
      apt:
        packages:
          - libqt4-dev
  - os: linux
    env: QT_VERSION=qt5 TRAVIS_DEPLOY=y
    compiler: clang
    addons:
      apt:
        packages:
          - qtbase5-dev
          - libqt5webkit5-dev
  - os: linux
    env: QT_VERSION=qt5
    compiler: gcc
    addons:
      apt:
        packages:
          - qtbase5-dev
          - libqt5webkit5-dev
  - os: osx
    env: QT_VERSION=qt5 TRAVIS_DEPLOY=y
    compiler: clang

install: source .travis/install.sh

script: ./.travis/script.sh

deploy:
  provider: releases
  api_key:
    secure: "TtNA74Zxji5UKKxXelf6erD9r1PbxKzW8bsf2sugANkWi/CBB1zOkxnuyTsHylwGL6R6WvagkGVHbNaYOfeR/DBQy4SRWBUnQ8ujByymIyIjGlUnvkYtTihW81SDrpoTYtYfok12HnqY+gTNvyfroTAHT3OBWcsb+m/jVh42Lwg="
  skip_cleanup: true
  file_glob: true
  file:
    - build/neuroscope*.deb
    - build/neuroscope*.dmg
  on:
    tags: true
    condition: "$TRAVIS_DEPLOY = y"
