language: cpp

os:
  - linux
  - osx

env:
  - QT_VERSION=qt4
  - QT_VERSION=qt5

install: source .travis/install.sh

script: ./.travis/script.sh

before_deploy: source .travis/deploy.sh

deploy:
  provider: releases
  api_key:
    secure: LdMU6bfPozM1sD+k/GVcTbmh+tlDuLzyQKbS38+3KOYhoVFVlOA2d1vymDI8BmQ66xSYa6yGBZ3Zu3MbV+aiukSNMp+QnS4q0mySxq7iUNdhEAI9a9GcljYvxo/Oj3BeJpksX6JgIhZK06wnafb1E6jdh6i1d+DldMK36PjMeVg=
  file_glob: true
  skip_cleanup: true
  file: "${RELEASE_PKG_FILE}"
  on:
    tags: true
    condition: "-z $RELEASE_PKG_FILE"
