language: cpp

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libqt4-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt; fi
  - git clone https://github.com/neurosuite/libneurosuite.git
  - cd libneurosuite
  - cmake .
  - make
  - sudo make install
  - cd ..

script:
  - mkdir build && cd build
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake ..;  fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake -DAPPBUNDLE=ON ..; fi
  - make && cpack

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export RELEASE_PKG_FILE=$(ls neuroscope_*.deb);  fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export RELEASE_PKG_FILE=$(ls neuroscope_*.dmg);  fi

deploy:
  provider: releases
  api_key:
    secure: LdMU6bfPozM1sD+k/GVcTbmh+tlDuLzyQKbS38+3KOYhoVFVlOA2d1vymDI8BmQ66xSYa6yGBZ3Zu3MbV+aiukSNMp+QnS4q0mySxq7iUNdhEAI9a9GcljYvxo/Oj3BeJpksX6JgIhZK06wnafb1E6jdh6i1d+DldMK36PjMeVg=
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  on:
    tags: true
